"""Add type column to Category

Revision ID: 81a7b5f32a2c
Revises: 76a53d188fdb
Create Date: 2025-06-09 19:33:34.348530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a7b5f32a2c'
down_revision = '76a53d188fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
